#!/bin/sh

all=.git-trim-all
keep=.git-trim-keep

cleanup() {
  rm $all $keep
}

branches=`git branch`

if [ $? != 0 ]; then
  exit 1
fi

echo "$branches" | grep -v '^*' | sed 's/^  //' | tee $all $keep > /dev/null

if [ `cat $all | wc -l` == 0 ]; then
  echo "No branches found to delete (cannot delete current branch)."
  cleanup
  exit 0
fi

eval $EDITOR $keep

delete=`diff --suppress-common-lines $all $keep | grep '^< ' | awk '{print $2}'`

echo $delete | xargs git branch -D

cleanup

